import React, { ReactNode } from "react";

import Head from "next/head";
import { AppProps } from "next/app";
import { Provider } from "react-redux";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { PersistGate } from "redux-persist/integration/react";
import { NextPage } from "next";

import { store, persistor } from "@/store";
import Layout from "@/layout";

import "../styles/globals.css";

type Page<P = {}> = NextPage<P> & {
  getLayout?: (page: ReactNode) => ReactNode;
};

type Props = AppProps & {
  Component: Page;
};

const App = ({ Component, pageProps }: Props) => {
  const [queryClient] = React.useState(() => new QueryClient());
  const getLayout = Component.getLayout ?? ((page) => <Layout>{page}</Layout>);
  return (
    <>
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <QueryClientProvider client={queryClient}>
            <ReactQueryDevtools />
            <>
              <Head>
                <title>Wedding Form</title>
                <meta name="description" content="Generated by Divory Team." />
              </Head>
              {getLayout(<Component {...pageProps} />)}
            </>
          </QueryClientProvider>
        </PersistGate>
      </Provider>
    </>
  );
};

export default App;
